debug: true

datasource:
  primary:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  secondary:
    url: jdbc:postgresql://localhost:5432/mediate
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

#采集延迟时间（分钟）
delay: 10